20220809-12:14:13.255 : connected
20220809-12:14:13.409 : Error on Session 'FIX.4.4:EXECUTOR->CLIENT1': System.IO.IOException: The process cannot access the file 'C:\Users\Guilherme\Desktop\Trabalhos do leo\Trabalho\FIX\Acceptor FIX\Acceptor_FIX\bin\Debug\net5.0\store\FIX.4.4-EXECUTOR-CLIENT1.session' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at QuickFix.FileStore.PurgeSingleFile(String filename)
   at QuickFix.FileStore.PurgeFileCache()
   at QuickFix.FileStore.Reset()
   at QuickFix.SessionState.Reset(String reason)
   at QuickFix.Session.NextLogon(Message logon)
   at QuickFix.Session.Next(MessageBuilder msgBuilder)
   at QuickFix.Session.NextMessage(String msgStr)
   at QuickFix.Session.Next(String msgStr)
   at QuickFix.SocketReader.OnMessageFoundInternal(String msg)
20220809-12:14:21.435 : SocketReader Error: Socket exception (127.0.0.1:57589): Foi forçado o cancelamento de uma conexão existente pelo host remoto.
20220809-12:14:21.436 : shutdown requested: Disconnected
20220809-12:14:21.439 : shutdown requested: Foi forçado o cancelamento de uma conexão existente pelo host remoto.
20220809-12:14:21.440 : shutdown
